spring:
  config:
    activate:
      on-profile: local
  batch:
    jdbc:
      initialize-schema: embedded
  datasource:
    url: jdbc:h2:tcp://localhost/~/batch
    username: sa
    password:
    driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: mysql
  batch:
    job:
     names: ${job.name:NONE}
     #enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch?serverTimezone=Asia/Seoul
    username: root
    password: 428653a
    driver-class-name: com.mysql.jdbc.Driver
